class config:
    block_args_EfficientNetB0 = [
        [
            {
                "block_type": "ds",
                "out_chs": 16,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 3,
                "pw_kernel_size": 1,
                "se_ratio": 0.25,
                "pw_act": False,
                "noskip": False,
            }
        ],
        [
            {
                "block_type": "ir",
                "out_chs": 24,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 24,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
        ],
        [
            {
                "block_type": "ir",
                "out_chs": 40,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 40,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
        ],
        [
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
        ],
        [
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
        ],
        [
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
        ],
        [
            {
                "block_type": "ir",
                "out_chs": 320,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            }
        ],
    ]

    block_args_EfficientNetB4 = [
        [
            {
                "block_type": "ds",
                "out_chs": 16,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 3,
                "pw_kernel_size": 1,
                "se_ratio": 0.25,
                "pw_act": False,
                "noskip": False,
            },
            {
                "block_type": "ds",
                "out_chs": 16,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 3,
                "pw_kernel_size": 1,
                "se_ratio": 0.25,
                "pw_act": False,
                "noskip": False,
            },
        ],
        [
            {
                "block_type": "ir",
                "out_chs": 24,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 24,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 24,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 24,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
        ],
        [
            {
                "block_type": "ir",
                "out_chs": 40,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 40,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 40,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 40,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
        ],
        [
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
        ],
        [
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
        ],
        [
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
        ],
        [
            {
                "block_type": "ir",
                "out_chs": 320,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 320,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
        ],
    ]

    block_args_EfficientNetB8 = [
        [
            {
                "block_type": "ds",
                "out_chs": 16,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 3,
                "pw_kernel_size": 1,
                "se_ratio": 0.25,
                "pw_act": False,
                "noskip": False,
            },
            {
                "block_type": "ds",
                "out_chs": 16,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 3,
                "pw_kernel_size": 1,
                "se_ratio": 0.25,
                "pw_act": False,
                "noskip": False,
            },
            {
                "block_type": "ds",
                "out_chs": 16,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 3,
                "pw_kernel_size": 1,
                "se_ratio": 0.25,
                "pw_act": False,
                "noskip": False,
            },
            {
                "block_type": "ds",
                "out_chs": 16,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 3,
                "pw_kernel_size": 1,
                "se_ratio": 0.25,
                "pw_act": False,
                "noskip": False,
            },
        ],
        [
            {
                "block_type": "ir",
                "out_chs": 24,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 24,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 24,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 24,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 24,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 24,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 24,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 24,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
        ],
        [
            {
                "block_type": "ir",
                "out_chs": 40,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 40,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 40,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 40,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 40,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 40,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 40,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 40,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
        ],
        [
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 80,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
        ],
        [
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 112,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
        ],
        [
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 192,
                "stride": 2,
                "act_layer": None,
                "dw_kernel_size": 5,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
        ],
        [
            {
                "block_type": "ir",
                "out_chs": 320,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 320,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 320,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
            {
                "block_type": "ir",
                "out_chs": 320,
                "stride": 1,
                "act_layer": None,
                "dw_kernel_size": 3,
                "exp_kernel_size": 1,
                "pw_kernel_size": 1,
                "exp_ratio": 6.0,
                "se_ratio": 0.25,
                "noskip": False,
            },
        ],
    ]

    efficientdet_d1 = dict(
        name="efficientdet_d1",
        backbone_name="efficientnet_b1",
        image_size=(640, 640),
        fpn_channels=88,
        fpn_cell_repeats=4,
        box_class_repeats=3,
        pad_type="",
        redundant_bias=False,
        backbone_args=dict(drop_path_rate=0.2),
        url="https://github.com/rwightman/efficientdet-pytorch/releases/download/v0.1/efficientdet_d1-bb7e98fe.pth",
    )
